### ISSUE TITLE
small typo

### ISSUE THREAD

**Issue by davecampbell** [justmarkham/DAT4#1]
seems like the choices are the same!
http://nbviewer.ipython.org/github/justmarkham/DAT4/blob/master/notebooks/08_linear_regression.ipynb

Confidence in our Model
Question: Is linear regression a high bias/low variance model, or a low variance/high bias model?

![cap- 2015-07-05 at 22 49 52](https://cloud.githubusercontent.com/assets/584933/8515022/91cf1396-2368-11e5-92fe-c1934b5105bb.png)

**Comment by brandonmburroughs** [comment]
Hey Dave!  Thanks for pointing this out.  It has been fixed.
